### ISSUE TITLE
Enchant reroll button sometimes causes it to target wrong item.

### ISSUE THREAD

**Issue by seutje** [ajseward/Ascension_Weakauras#4]
I put a blue item from my bags into the reforge slot, hit reforge and it reforged my equipped helmet.
I put a blue item from my bag into the reforge slot, hit extract and it destroyed my equipped chest piece.

**Comment by ajseward** [comment]
This issue was with ascensions patches. You need to update from the launcher.

**Comment by seutje** [comment]
Yeah, just disabled WA and it still destroyed another chest piece q.q
