### ISSUE TITLE
Add slight delay in auto-learn from book

### ISSUE THREAD

**Issue by seutje** [ajseward/Ascension_Weakauras#5]
Hey,

I've noticed that the auto-learn from book weakaura causes it to not always update the skills on your bars, but only when there's a bunch of skills to learn. So I would like to suggest adding a slight delay, although I'm not sure that will fix it.

**Comment by ajseward** [comment]
This is likely a server or client issue. I've experienced the same on warmane using the train all button w/ elvui. 

Might add a config for it later to slow it down but for now I'm going to leave as is, if its even still an issue.
