### ISSUE TITLE
Target on Nameplate

### ISSUE THREAD

**Issue by Calyus** [ajseward/Ascension_Weakauras#6]
There is a weak aura called Nameplate's Target that shows the name of the player a mob is aggroed on in TBC classic. The code does not work in Ascension though it uploads fine. Could you possibly make one similar?

This was the link for the WA: https://wago.io/VWoreWgtk - it says 404 not found but this is the code that works in classic if you can somehow just modify it to work. I would appreciate it

!WA:2!9M1ZZTTX1)iProQ0XTY)iQjXXnWmXQuJLPLOKCC8e75ljfPeZijQaszLmUEibbwsGkqa0DxQFy7COA6HEWtoOtFBU0P8qp1t8qo3XhYmPN2rtp2tA6FbU)d03BbieOeLSLNmfZyrG3(23VFFElGhi)LAEjJlz8hl0Mt2MNAvxlhETS5wPCo19rktN31HxY6jKpEFTwCtxArpULRd7FKN2IrwrRjPAgKpVR(m98W1utLpF6vYUyrvLs5kxUWklu6zQz474rQzs0miu1TSm4MdLxmshdctNAjL3U1dutTMedRwnfNZBouGO4MAQ0o6GMv8qJJPOrjk1HhDCDu0joCkXqXWI5zRTZZOIydVPyKAmInrNtni11AzZpFghWq9UwxjMpFzWKv0Ii2NrtTbzN9qxrgdqVBEW(mRTPMDlc77QLPy5YfxUJ)pklLlF5xeCVAHfwSSyWminv5dPkxC1DH)jzBp8gFEInuDXiIFHy0liU8bsBYwJtKkum23j(LI3t8(IbfFG4QIpuCnXVsCrV4hA0R0DdhXYbX(9uMBD(YwolDoXiQunNgeAnRgL4eVvhAQKtNQP22)ygw3hHDKQPK5l6DLdvWxP4wVoJaI0xCWEexMUDrjrXON)7fxhLViU4J9fZN8JIB0vGIXpQ4(6qXjsGcANUcAGFqCD)TfvwdhkRHfJ7F3f3LBsD5CBIiXWI31uCzXKIrX1MdkGe)mX5gumSjO8hc5CUBJgaJJwfSIpX3kUtDd9L12GOWm1AQ5WuAqjAqIVHMLdyvxUDdxxd)kAqRGqe3smQP4IDk0WXfkZGYO6IlNr(JCDvMNMoz)n1OwA1SjRJ1YvHkBRgM83fyzpOSzr5tvrPLsmtvXS4cI5QkU5I)FpL)(38)8xgQJFc0pXpyQwuBVRAY5ES7D7BVLwd3KwU3(HRdwW6n4BC7uzS0DDQ(cz)yohuXgvF5geIxAMhuMRQboG5EOvgirVrL8MfAQapTj0KuRWkLkmFU9Ay7UvwxBx6xmeCLbB78E3066wgatA2kRsjm8E9DoqciGT)5T1AWOfxR8sfwjxgBxnJ)k1YPb1TLxm0HR4q2KqnRb7heYyQnHwoRyzqBBmXIWnqFnEdTUMogQhRgd2UnrDrxOdTdkHGvQkfNMT1MKQQ62Am24ILORNg6QkQkwCmXxwL(exhsbd2G7IUszayz)AT4CxNIGnaqa7dPAd3T(k)ATHoieet6fISTPKgGMWnko3(H(iI9mT3v0DDTHD7G4dZBXKHAZmaYNB12CxDqfmyZJS5VrMmsfKmmRb5N6wn2umTPysz5P4kNxC7QIjoV4Mdi(Ol0jaGQaWyTPNzUzsDxi8XTTCiISQ6HjK26TyC3MO69()R3Yrgvsmrmf4YQUIwlQwfIZMjzCegGBsCKlHx2U6q(dwqFdMY9pcRjdO)aLPaWdJtyvasjE8qbsj8wuNajkPsCmIb)lie)1(H4p8T2VBuR0wwEKQEJEOtSMNbi)ATK)8IU8LZObX8fqQoSA08LqDlH6Oz)q)qmzpnhRMyHTZDubtGYHg(maKpzFdW2r6vWPkugbcPgSxq0yKsWSaNgCZ3Ex8jzkUzMMqhacw0u4iCfEVT43jAwRULJfZ8OKpGXT03yN5duGjniFpCBwRAQY6g2hmMyK9HhRbrfSfWXqm7c721ZQMQLLrNzFId9l(S1TBA0q8ot43mMksZO4bExnOGadsvGPzGRwXj4grZ2bTVDll2lSkUDUT9Gwu2wA70UU12edje0F4DAhOJWo7N462CaF5ibfcgC5phAIf)7lFTp6F9Vj)59c7a8gnp16jkFzlndW91ukdJRwagK2eccQtNeGJvLsl(n0ZG5ntQFpl7oc7XR5NY3EGF)XRs7t9wDkmk7WYx)s3G5mrRD9BRs2DfO(CUiByNtCd7C4gMsUHqg87(Vxjc3)qfjcl3dzjc28JoQGdpFWJN84BmIVn5ztS9EuGhl38eNKH77Bjcckt2nmmb2AglwS9mCR4NnQMbQY5JlE(2d8Lrmsx8at3x5PFtSy9Z4WLKQ(rt)y4(4(1nX99OhLkcn8WnDPpte6YASUlmRCb)tu2L2CsAr3(DKu6zJFQKeC2PUeUBxcr34N1Ly39cEv0sWGa8HZ5pSQtnDH5RKDP0LkvjBXLkQw6rXlTy6LtVsCuMzXtkqKnujMk5utQmvYzNf)7D)uzKw8TvfW0PNpO4Bn7ePzo(nCO)wi8BvFhXhi7ysf)gEXTm8Uu453(1mLYA0ge(UCQvd4OASF(40GB)bat65D8tGseUoYYkFeuvyqlmlFrIMn3ufRAyXoaaJKKHr3aIGAPvZT0s(uyEgRNUYkPxo3QlLUCoWzlwk38kiHk(uwBLcLRKE(57dv1Clx8H9sp9AQ(IRKsEvK8ARopqFxysVTnmtowMwqbxnmuayg6Me9ne)Pq7RuR6G91Ps20LkxPu50QLHkZlC9WPCs)KnPIK5jvqrnPsYKjdN(jxq5(q(UpEv8ENgIVGGfKgNEsLzNsXWnCHdHpqfGfpHnFXbTPy1dNGwxdyl32wmolbUJjK4ziXSAoP54WXeX9944(g9e9AjDVYwPSvtcnz66WGoOKcSSdhWRSorBJ0qrllzjDnNCYSxI49n2hQgOkCIEudcaC077(7XdI9TmiU09KHMxPFkfjeN7RiJyVHIuUH(COLfwRW8qMavgEBIdLEGrlz4yr1JGP9iKlS1nuv9QfUSLly9KjJFlFcXpLeUphNqcTpWm4rWdJBfy4FJe0IkTUNUcErtsp5TETzS2eS4eXFWnyFE8jUN)besGcgrt6AGt0pJZ3gwvQ9t3tWRtqtqNww8C4sGWtxL9Zlogb)M8Wu1tpnBXPNbPrVckyWF6pdb92smK(YG)jqay(kOtTk2(NCbcp8H8Uuz2twk2Fr4rDBGhfdpNjIJGUMLE8(Zm(kelcVyfWiMY7pt6M4lUBCQ8WmD36ez4BE1Wb2mYPIcea7hbh4m3Wg(MiC0DJMXJ2t3NxHjSajzGxwxdm3(SCVbQy9ZH79COrWhETHrCSSpr00EcHrNfgVFHlGeI9JvSeoExIEq3CC5hAeqZM8CR9s4ZdLXTogOt3prYX9mCiOShXprA5O4PzrzjoIhpXrNpEQOUNHS8Big8Baw8)BWK)jcB(ngJ(NoS6tdZ(eXUF1nV9fTpze48xdUpHE7Jz5hfz4nAsZzAQZzAc0zAA0pXtMEJNsDMNyDwNE9Apj7KNQ96u(gmL71Ok9vmU5nQ8SFw1rPDAhvpcme(MMTni1GxDctG0fZT0Q5xBP9A5e86IX8Ui(zy2Ku2)5LDni)T3QJSiQeh)qod9s)xUppscfsTszvZLBLD3YLASovZB31dUbuetJJF8lIj1Yb)4xetvnBptTH64)n)8)atdmWad1g)SBwYpauSowo(qq4h3179SKF88G)JIKVktok1LYQEawtHSPl)QvzsdpEjM6mjtLCMlT5)8R(V

**Comment by ajseward** [comment]
Nameplates are just too different between 3.3.5 (the version of wow ascension uses) and modern wow (6.0+).

Both classic versions run the same UI code as retail.

Sorry!
