### ISSUE TITLE
I want to thank you!

### ISSUE THREAD

**Issue by BanditTech** [ajseward/Ascension_Weakauras#7]
This is an amazing repository and really want to tip my hat to you, kudos on these amazing mini scripts!

The mystic altar rolling is going to help me out immensely, and I could not thank you enough for what you have created for this. I will have to dabble with the other tools you have made, by my goodness I am so happy to find this.

**Comment by BanditTech** [comment]
I was hoping to ask you, how did you figure out what function calls are available, such as `CAO_Spell_References` or `IsSpellRE()`?

**Comment by ajseward** [comment]
There are ways to browse the interface code for ascension using an mpq editor.

**Comment by BanditTech** [comment]
thanks for the information, I am new to making code for WOW and the help is appreciated.
